# Generated by Django 4.1.6 on 2023-02-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('random_img', models.ImageField(default=100, upload_to='')),
            ],
        ),
    ]
