# Generated by Django 4.1.6 on 2023-02-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='random_img',
            field=models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100),
        ),
    ]
